Repository FalsyQuiz/FalsyQuiz, pull requests merged in 2018-04, with the labels that each got.

#25 Feature/falsy quiz 19 add questions
  app/src/main/java/hu/falsyquiz/falsyquiz/DataPersister/Entities/Utils/QuestionInitializer.java
Labels: feature

#26 Feature/falsy quiz 22 app icon
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-hdpi/launcher.png
  app/src/main/res/mipmap-mdpi/launcher.png
  app/src/main/res/mipmap-xhdpi/launcher.png
  app/src/main/res/mipmap-xxhdpi/launcher.png
  app/src/main/res/mipmap-xxxhdpi/launcher.png
Labels: feature

#29 Bug/falsy quiz 28 nullpointer
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/QuestionActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Game/GameReferee.java
Labels: bug

#35 Feature/falsy quiz 32 navigation drawer
  app/build.gradle
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/MainMenuActivity.java
  app/src/main/res/drawable/shapes.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/mipmap-hdpi/ic_assessment_black_24dp.png
  app/src/main/res/mipmap-hdpi/ic_help_black_24dp.png
  app/src/main/res/mipmap-hdpi/ic_play_circle_outline_black_24dp.png
  app/src/main/res/mipmap-mdpi/ic_assessment_black_24dp.png
  app/src/main/res/mipmap-mdpi/ic_help_black_24dp.png
  app/src/main/res/mipmap-mdpi/ic_play_circle_outline_black_24dp.png
  app/src/main/res/mipmap-xhdpi/ic_assessment_black_24dp.png
  app/src/main/res/mipmap-xhdpi/ic_help_black_24dp.png
  app/src/main/res/mipmap-xhdpi/ic_play_circle_outline_black_24dp.png
  app/src/main/res/mipmap-xxhdpi/ic_assessment_black_24dp.png
  app/src/main/res/mipmap-xxhdpi/ic_help_black_24dp.png
  app/src/main/res/mipmap-xxhdpi/ic_play_circle_outline_black_24dp.png
  app/src/main/res/mipmap-xxxhdpi/ic_assessment_black_24dp.png
  app/src/main/res/mipmap-xxxhdpi/ic_help_black_24dp.png
  app/src/main/res/mipmap-xxxhdpi/ic_play_circle_outline_black_24dp.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#37 FalsyQuiz-36: Created Nav drawer's button and redesigned main app page.
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/AbstractActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/MainMenuActivity.java
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/mipmap-hdpi/ic_menu_white_24dp.png
  app/src/main/res/mipmap-mdpi/ic_menu_white_24dp.png
  app/src/main/res/mipmap-xhdpi/ic_menu_white_24dp.png
  app/src/main/res/mipmap-xxhdpi/ic_menu_white_24dp.png
  app/src/main/res/mipmap-xxxhdpi/ic_menu_white_24dp.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feature

#39 FalsyQuiz-16: Next question implemented
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/QuestionActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Game/GameReferee.java
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#62 Feature/falsy quiz 61 design gameover
  app/src/main/AndroidManifest.xml
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/GameOverActivity.java
  app/src/main/res/font/blackhansans_regular.ttf
  app/src/main/res/font/fonts.xml
  app/src/main/res/font/indieflower_regular.ttf
  app/src/main/res/font/lobster_regular.ttf
  app/src/main/res/font/nunito.xml
  app/src/main/res/font/orbitron_regular.ttf
  app/src/main/res/font/sacramento_regular.ttf
  app/src/main/res/layout/activity_game_over.xml
  app/src/main/res/layout/activity_main_menu.xml
  app/src/main/res/mipmap-hdpi/failed.png
  app/src/main/res/mipmap-hdpi/winner.png
  app/src/main/res/mipmap-mdpi/failed.png
  app/src/main/res/mipmap-mdpi/winner.png
  app/src/main/res/mipmap-xhdpi/failed.png
  app/src/main/res/mipmap-xhdpi/winner.png
  app/src/main/res/mipmap-xxhdpi/failed.png
  app/src/main/res/mipmap-xxhdpi/winner.png
  app/src/main/res/mipmap-xxxhdpi/failed.png
  app/src/main/res/mipmap-xxxhdpi/winner.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#63 FalsyQuiz-41: All the buttons are the same size
  app/src/main/res/layout/activity_question.xml
Labels: feature

#67 FalsyQuiz-64: rounded buttons
  app/src/main/res/drawable/answer_button.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/values/colors.xml
Labels: task

#69 Feature/falsy quiz 33 design questions
  app/src/main/AndroidManifest.xml
  app/src/main/res/font/bitter_regular.ttf
  app/src/main/res/font/fonts.xml
  app/src/main/res/layout/activity_game_over.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#76 Bug/falsy quiz 68 time and sound problems
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/AbstractActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/QuestionActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Application/BaseApplication.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Components/MainComponent.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Game/GameReferee.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Moduls/VibratorEngineModule.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Tools/VibratorEngine.java
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/raw/female_giving_birth.mp3
Labels: bug

#86 FalsyQuiz-79: Wrote javadoc for all of the classes.
  app/src/main/java/hu/falsyquiz/falsyquiz/Actions/Actions.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/AbstractActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/GameOverActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/HelpActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/MainMenuActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/QuestionActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/ResultsActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Activities/SplashActivity.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Application/BaseApplication.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Components/MainComponent.java
  app/src/main/java/hu/falsyquiz/falsyquiz/DataPersister/Entities/Configuration.java
  app/src/main/java/hu/falsyquiz/falsyquiz/DataPersister/Entities/Game.java
  app/src/main/java/hu/falsyquiz/falsyquiz/DataPersister/Entities/InfoTextMessage.java
  app/src/main/java/hu/falsyquiz/falsyquiz/DataPersister/Entities/Managers/DataManager.java
  app/src/main/java/hu/falsyquiz/falsyquiz/DataPersister/Entities/Managers/DatabaseManager.java
  app/src/main/java/hu/falsyquiz/falsyquiz/DataPersister/Entities/Question.java
  app/src/main/java/hu/falsyquiz/falsyquiz/DataPersister/Entities/Utils/QuestionInitializer.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Game/GameReferee.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Game/Timer.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Moduls/ApplicationModule.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Moduls/StorageModule.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Moduls/VibratorEngineModule.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Tools/SongPlayer.java
  app/src/main/java/hu/falsyquiz/falsyquiz/Tools/VibratorEngine.java
Labels: task
